### ISSUE TITLE
variabile cu litere mari... trist

### ISSUE THREAD

**Issue by stefanbulzan** [cezarhre/homeworkcurs8#4]
https://github.com/cezarhre/homeworkcurs8/blob/adce173f9b178692d23b84ebcce16e12839bbd53/src/ro/fasttrackit/curs8/homework2/interfaces/BankMain.java#L5

**Comment by cezarhre** [comment]
Am refacut complet exercitiul 2

**Comment by cezarhre** [comment]
Am sters din greaseala exercitiul si l-am facut din nou
