### ISSUE TITLE
mai trebuia un alt obiect.. Person sau Customer care sa foloseasca BankServices

### ISSUE THREAD

**Issue by stefanbulzan** [cezarhre/homeworkcurs8#5]
https://github.com/cezarhre/homeworkcurs8/blob/adce173f9b178692d23b84ebcce16e12839bbd53/src/ro/fasttrackit/curs8/homework2/interfaces/BankMain.java#L5

**Comment by cezarhre** [comment]
Am refacut complet exercitiul
